{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "yossarian-go.fullname" . }}-tls
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "yossarian-go.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: {{ .Values.ingress.tls.certManager.issuerName }}
    kind: {{ .Values.ingress.tls.certManager.issuerKind }}
  dnsNames:
  - {{ .Values.ingress.fqdn }}
{{- end }}
