---
# Database PVC (SQLite)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yossarian-go-db-pvc
  namespace: yossarian-go
  labels:
    app: yossarian-db-service
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: 

---
# MinIO Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-minio-0
  namespace: yossarian-go
  labels:
    app: minio
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: 
