apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yossarian-go-tls
  namespace: yossarian-go
  labels:
    app: yossarian-go
spec:
  secretName: yossarian-go-tls
  issuerRef:
    name: my-cluster-issuer  # CHANGE THIS to your ClusterIssuer name
    kind: ClusterIssuer
  dnsNames:
  - yossarian-go.mydomain.local  # CHANGE THIS to your domain
