apiVersion: batch/v1
kind: CronJob
metadata:
  name: yossarian-ad-sync
  namespace: yossarian-go
  labels:
    app: yossarian-go
    component: cronjob
spec:
  # Run daily at 01:00
  schedule: "0 1 * * *"
  
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: yossarian-go
            component: cronjob
        spec:
          containers:
          - name: curl
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - curl -X POST http://yossarian-db-service:8081/ldap/sync-full
          
          restartPolicy: OnFailure
